# Generated by Django 3.0.5 on 2020-04-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Stat',
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name_plural': 'Cover'},
        ),
        migrations.AlterModelOptions(
            name='interpret',
            options={'ordering': ['nazev'], 'verbose_name_plural': 'Interpret'},
        ),
        migrations.AlterModelOptions(
            name='objednavka',
            options={'ordering': ['zakaznik__email'], 'verbose_name_plural': 'Objednávka'},
        ),
        migrations.AlterModelOptions(
            name='polozka',
            options={'ordering': ['interpret__nazev', '-rok_vydani'], 'verbose_name_plural': 'Položka'},
        ),
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ['name'], 'verbose_name_plural': 'Stát'},
        ),
        migrations.AlterModelOptions(
            name='vydavatelstvi',
            options={'ordering': ['nazev', 'vznik'], 'verbose_name_plural': 'Vydavatelství'},
        ),
        migrations.AlterModelOptions(
            name='zakaznik',
            options={'ordering': ['last_name', 'first_name', 'stat'], 'verbose_name_plural': 'Zákazník'},
        ),
        migrations.AlterModelOptions(
            name='zanr',
            options={'ordering': ['name'], 'verbose_name_plural': 'Žánr'},
        ),
        migrations.RenameField(
            model_name='zakaznik',
            old_name='country',
            new_name='stat',
        ),
    ]
