# Generated by Django 3.0.5 on 2020-04-29 10:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200429_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polozka',
            name='cover',
        ),
        migrations.AddField(
            model_name='polozka',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.cover_path, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(help_text='Vložte prosím celý název státu.', max_length=100, unique=True, verbose_name='Název státu'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='stat',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='app.Stat', verbose_name='Stát'),
        ),
        migrations.AlterField(
            model_name='zanr',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
