# Generated by Django 3.0.5 on 2020-04-29 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200429_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vydavatelstvi',
            name='vlastnik',
        ),
        migrations.AlterField(
            model_name='interpret',
            name='nazev',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='nazev',
            field=models.ManyToManyField(to='app.Polozka', verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='objednavka',
            name='zakaznik',
            field=models.ManyToManyField(to='app.Zakaznik', verbose_name='Zákazník'),
        ),
        migrations.AlterField(
            model_name='polozka',
            name='nazev',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='polozka',
            name='rok_vydani',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2020)], verbose_name='Rok vydání'),
        ),
        migrations.AlterField(
            model_name='polozka',
            name='stopaz',
            field=models.IntegerField(help_text='Zadejte délku stopáže v minutách.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stopáž'),
        ),
        migrations.AlterField(
            model_name='polozka',
            name='zanr',
            field=models.ManyToManyField(to='app.Zanr', verbose_name='Žánr'),
        ),
        migrations.AlterField(
            model_name='vydavatelstvi',
            name='nazev',
            field=models.CharField(max_length=200, unique=True, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='vydavatelstvi',
            name='sidlo',
            field=models.ForeignKey(blank=True, on_delete=models.SET(''), to='app.Stat', verbose_name='Sídlo'),
        ),
        migrations.AlterField(
            model_name='vydavatelstvi',
            name='vznik',
            field=models.IntegerField(help_text='Hodnoty lze zadávat v rozmezí 1800 až 2020.', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='zanr',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Žánr'),
        ),
    ]
